# Functions

In [ ]:
a = np.array([2,4,3,6,5,8,7,9,1,0])
a

array([2, 4, 3, 6, 5, 8, 7, 9, 1, 0])

In [ ]:
a.sort()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
s = np.square(a)
s

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
np.sqrt(s)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.sqrt(16)

4.0

In [ ]:
np.sqrt([4,9])

array([2., 3.])

In [ ]:
a = np.array([8,27,64])
np.cbrt(a)

array([2., 3., 4.])

In [ ]:
np.abs([-1,2,3,-5,-6,-2,6])

array([1, 2, 3, 5, 6, 2, 6])

In [ ]:
abs(-8)

8

In [ ]:
np.add([1,2,3],[4,5,6])

array([5, 7, 9])

In [ ]:
np.subtract([4,5,6],[1,2,3])

array([3, 3, 3])

In [ ]:
np.multiply([1,2,3],[2,3,4])

array([ 2,  6, 12])

In [ ]:
a1 = np.array([2,1,4,5,3,6])
a2 = np.array([3,4,2,1,6,5])

In [ ]:
np.maximum(a1,a2)

array([3, 4, 4, 5, 6, 6])

In [ ]:
np.minimum(a1,a2)

array([2, 1, 2, 1, 3, 5])

In [ ]:
a1 > a2

array([False, False,  True,  True, False,  True])

In [ ]:
np.greater(a1,a2)

array([False, False,  True,  True, False,  True])

In [ ]:
np.less(a1,a2)

array([ True,  True, False, False,  True, False])

In [ ]:
a1 = np.arange(21)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
np.mean(a1)

10.0

In [ ]:
np.mean([1,2,3,4,5,6,7,8,9])

5.0

In [ ]:
np.var([1,2,3,4,5,6,7,8,9])

6.666666666666667

In [ ]:
np.std([1,2,3,4,5,6,7,8,9])

2.581988897471611

In [ ]:
np.median(a1)

10.0

In [ ]:
a1.mean()

10.0

In [ ]:
a1.var()

36.666666666666664

In [ ]:
a1.std()

6.0553007081949835

In [ ]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [ ]:
a.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a.min()

1

In [ ]:
a.max()

10

In [ ]:
a.sum()

55

In [ ]:
a = np.arange(64).reshape(8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [ ]:
a.shape

(8, 8)

In [ ]:
a.mean()

31.5

In [ ]:
a.mean(axis = 0) # column wise avg

array([28., 29., 30., 31., 32., 33., 34., 35.])

In [ ]:
a.mean(axis = 1) # row wise avg

array([ 3.5, 11.5, 19.5, 27.5, 35.5, 43.5, 51.5, 59.5])

In [ ]:
a.std()

18.472953201911167

In [ ]:
a.std(axis = 0)

array([18.33030278, 18.33030278, 18.33030278, 18.33030278, 18.33030278,
       18.33030278, 18.33030278, 18.33030278])

In [ ]:
a.std(axis = 1)

array([2.29128785, 2.29128785, 2.29128785, 2.29128785, 2.29128785,
       2.29128785, 2.29128785, 2.29128785])

In [ ]:
a.max()

63

In [ ]:
a.max(axis = 0)

array([56, 57, 58, 59, 60, 61, 62, 63])

In [ ]:
a.max(axis = 1)

array([ 7, 15, 23, 31, 39, 47, 55, 63])

In [ ]:
x = np.array([10,30,80,20,40])
x

array([10, 30, 80, 20, 40])

In [ ]:
np.argmax(x)             # returns the index of maximum element

2

In [ ]:
np.argmin(x)             # returns the index of minimum element

0

In [ ]:
a1 = np.array([2,1,5,4,3,5,6,7,3,10,2,3]).reshape(3,4)
a1

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [ ]:
np.argmax(a1)

9

In [ ]:
np.argmax(a1, axis = 0)

array([1, 2, 1, 1])

In [ ]:
np.argmax(a1, axis = 1)

array([2, 3, 1])

In [ ]:
np.argmin(a1, axis = 0)

array([0, 0, 2, 2])

In [ ]:
np.argmin(a1, axis = 1)

array([1, 0, 2])

In [ ]:
a1

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [ ]:
a1.ravel()         # Converts to single dimension

array([ 2,  1,  5,  4,  3,  5,  6,  7,  3, 10,  2,  3])

In [ ]:
a2 = a1.reshape(1,12)
a2

array([[ 2,  1,  5,  4,  3,  5,  6,  7,  3, 10,  2,  3]])

In [ ]:
a2.ndim

2

In [ ]:
a2.shape

(1, 12)

In [ ]:
a2 = a2.squeeze()
a2

array([ 2,  1,  5,  4,  3,  5,  6,  7,  3, 10,  2,  3])

In [ ]:
a2.shape

(12,)

In [ ]:
a2 = a2.reshape(3,4,1)
a2

array([[[ 2],
        [ 1],
        [ 5],
        [ 4]],

       [[ 3],
        [ 5],
        [ 6],
        [ 7]],

       [[ 3],
        [10],
        [ 2],
        [ 3]]])

In [ ]:
a2 = a2.squeeze()
a2

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [ ]:
a2.shape

(3, 4)

In [ ]:
np.linspace(1,10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [ ]:
a = np.empty((2,3), dtype = int)
a

array([[    132355895080535,                   0,                 101],
       [4189017755886051700, 8027140907415206688, 7018332503360695925]])

### Concatenation

In [ ]:
a1 = np.arange(5)
a2 = np.arange(5,10)

In [ ]:
np.concatenate((a1,a2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1 = np.arange(12).reshape(4,3)
a2 = np.arange(12,24).reshape(4,3)
print(a1)
print(a2)

In [ ]:
np.concatenate((a1,a2))

In [ ]:
np.concatenate((a1,a2), axis = 0)

In [ ]:
np.concatenate((a1,a2), axis = 1)

In [ ]:
a1 = a
a2 = a.T
print(a1)
print()
print(a2)

In [ ]:
np.concatenate((a1,a2), axis = 0)

In [ ]:
np.concatenate((a1,a2), axis = 1)

## Random numbers

In [ ]:
np.random.randint(1,10)

In [ ]:
np.random.randint(50)

In [ ]:
np.random.randint(1,100,10)

In [ ]:
np.random.randint(11,100,(10,10))

In [ ]:
np.random.rand(10)

In [ ]:
np.random.randn(10)

In [ ]:
np.random.randn(3,4)

# Conditional Indexing

In [ ]:
a = np.random.randint(11,100,(8,8))
a

In [ ]:
a > 50

In [ ]:
a[a > 50]

In [ ]:
a[a < 50]

In [ ]:
a[a <= 40]

In [ ]:
a[a == 16]

# Slicing in Multidimensional Arrays

In [ ]:
a = np.random.randint(10,100,(12,12))
a

In [ ]:
a[0:5]

In [ ]:
a[6:11]

In [ ]:
a[-6:-1]

In [ ]:
a[0:6,0:4]

In [ ]:
a[2:9:2, 3:8:2]

In [ ]:
a[10:3:-1, 5:10]

In [ ]:
# Take marks of two students in 5 subjects as input and calculate the absolute difference in marks of corresponding subjects
student1 = list(map(int, input('Enter the marks in five subjects for student 1: ').split()))
student2 = list(map(int, input('Enter the marks in five subjects for student 2: ').split()))

student1 = np.array(student1)
student2 = np.array(student2)
diff = np.abs(student1 - student2)
diff